# Generated by Django 5.2.13 on 2026-04-29 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PasswordResetCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code_hash", models.CharField(max_length=128)),
                ("expires_at", models.DateTimeField()),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="password_reset_codes",
                        to="users.user",
                    ),
                ),
            ],
            options={
                "db_table": "password_reset_codes",
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddIndex(
            model_name="passwordresetcode",
            index=models.Index(
                fields=["user", "expires_at"], name="idx_reset_code_user_exp"
            ),
        ),
        migrations.AddIndex(
            model_name="passwordresetcode",
            index=models.Index(fields=["expires_at"], name="idx_reset_code_exp"),
        ),
    ]
