# Generated by Django 5.2.13 on 2026-04-26 13:29

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('provider', models.CharField(choices=[('mock', 'Mock'), ('stripe', 'Stripe')], max_length=20)),
                ('payment_method', models.CharField(choices=[('cod', 'Cash on Delivery'), ('card', 'Card')], default='card', max_length=20)),
                ('status', models.CharField(choices=[('initialized', 'Initialized'), ('requires_payment_method', 'Requires payment method'), ('requires_action', 'Requires action'), ('processing', 'Processing'), ('succeeded', 'Succeeded'), ('canceled', 'Canceled'), ('completed', 'Completed')], default='initialized', max_length=40)),
                ('currency', models.CharField(default='usd', max_length=10)),
                ('cart_signature', models.CharField(max_length=64)),
                ('shipping_signature', models.CharField(max_length=64)),
                ('shipping_snapshot', models.JSONField(default=dict)),
                ('cart_snapshot', models.JSONField(default=list)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('provider_payment_id', models.CharField(blank=True, max_length=255)),
                ('idempotency_key', models.CharField(default=uuid.uuid4, max_length=64, unique=True)),
                ('last_error_code', models.CharField(blank=True, max_length=100)),
                ('last_error_message', models.CharField(blank=True, max_length=255)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('payment_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'checkout_sessions',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='order',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_initiated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Cash on Delivery'), ('card', 'Card')], default='cod', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('canceled', 'Canceled'), ('refunded', 'Refunded')], default='unpaid', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='transaction_reference',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['payment_status'], name='idx_orders_payment_status'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['payment_method'], name='idx_orders_payment_method'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['transaction_reference'], name='idx_orders_txn_ref'),
        ),
        migrations.AddField(
            model_name='checkoutsession',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkout_session', to='orders.order'),
        ),
        migrations.AddField(
            model_name='checkoutsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkout_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='checkoutsession',
            index=models.Index(fields=['user'], name='idx_checkout_session_user'),
        ),
        migrations.AddIndex(
            model_name='checkoutsession',
            index=models.Index(fields=['status'], name='idx_checkout_session_status'),
        ),
        migrations.AddIndex(
            model_name='checkoutsession',
            index=models.Index(fields=['provider'], name='idx_checkout_session_provider'),
        ),
        migrations.AddIndex(
            model_name='checkoutsession',
            index=models.Index(fields=['provider_payment_id'], name='idx_checkout_pay_id'),
        ),
        migrations.AddIndex(
            model_name='checkoutsession',
            index=models.Index(fields=['cart_signature'], name='idx_checkout_session_cart'),
        ),
        migrations.AddConstraint(
            model_name='checkoutsession',
            constraint=models.CheckConstraint(condition=models.Q(('subtotal__gte', 0)), name='checkout_session_subtotal_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='checkoutsession',
            constraint=models.CheckConstraint(condition=models.Q(('total_price__gte', 0)), name='checkout_session_total_non_negative'),
        ),
    ]
