# Generated by Django 5.2.13 on 2026-04-28 07:20

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('discount_type', models.CharField(choices=[('percent', 'Percent'), ('fixed', 'Fixed')], default='percent', max_length=10)),
                ('discount_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('expires_at', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'coupons',
                'ordering': ('used', 'expires_at', '-created_at'),
                'indexes': [models.Index(fields=['user'], name='idx_coupons_user'), models.Index(fields=['code'], name='idx_coupons_code'), models.Index(fields=['used'], name='idx_coupons_used'), models.Index(fields=['expires_at'], name='idx_coupons_expires')],
                'constraints': [models.UniqueConstraint(fields=('user', 'code'), name='uniq_coupon_user_code'), models.CheckConstraint(condition=models.Q(('discount_value__gt', 0)), name='coupon_discount_positive')],
            },
        ),
    ]
